### ISSUE TITLE
HLT migration to stage-2 L1T

### ISSUE THREAD

**Issue by Martin-Grunewald** [cms-tsg-storm/cmssw#3]
Need replacement for summary report module L1GtTrigReport - the module L1TGlobalAnalyzer does not apply to do what I need: and end-of-run/job summary report a la L1GtTrigReport.
One line per algo with event counts for accept/reject, and possibly also before/after prescale, before/after mask.

**Comment by Martin-Grunewald** [comment]
Need more PRs beyond 800:
https://github.com/cms-sw/cmssw/pull/13257
https://github.com/cms-sw/cmssw/pull/13316
https://github.com/cms-sw/cmssw/pull/13340    # now in 80X IB
Need to make another PR collecting the HLT code changes.

**Comment by Martin-Grunewald** [comment]
L1T menus need fixing AND need to go into the release (as long as we need xml for lack of o2o).
But David Lange is blocking this, eg, here: cms-sw#13316

**Comment by Martin-Grunewald** [comment]
According to ConfDB, the master table now only contains the remaining following references to the 
hltL1extraParticles collections: instances of these plugins:

```
HLTEgammaL1MatchFilterRegional
HLTEcalRecHitInAllL1RegionsProducer
EgammaHLTCaloTowerProducer

HLTMuonL1Filter
HLTL1MuonSelector
L2MuonSeedGenerator

CaloTowerCreatorForTauHLT

HLTPFJetL1MatchProducer

IsolatedPixelTrackCandidateProducer
```

Of course, this is HLT only! Reco and DQM contain many more plugins.

Further modules under HLTrigger:

```
HLTEgammaL1MatchFilterPairs
PFJetsMatchedToFilteredCaloJetsProducer
HLTJetL1MatchProducer
HLTSinglet
HLTMuonL1RegionalFilter
HLTMuonL1toL3TkPreFilter
HLTMuonL2ToL1Map
HLTMuonTrkFilter
HLTPixelIsolTrackFilter
```

(rekovic added a migrated HLTMuonL1Filter plugin called HLTMuonL1TFilter...)

L1T Migration (non-l1extra) is also needed for these: 

```
HLTPrescaler                          # done in my area
TriggerResultsFilter
TriggerResultsFilterFromDB
```

**Comment by fwyzard** [comment]
Hi Martin,
I remember I found some more and listed them in the news some times ago... can you check against that list as well ?
Maybe there are modules which make use of the hltGtDigis, in addition to the "extra particles" ?
Those would need to be migrated to the new L1 collections as well.

**Comment by Martin-Grunewald** [comment]
@fwyzard 
I could only find your email:

```
Date: Wed, 20 Jan 2016 01:43:06
From: Andrea Bocci <fwyzard@gmail.com>
To: Vladimir Rekovic <Vladimir.Rekovic@cern.ch>,
    Michael Mulhearn <mulhearn@physics.ucdavis.edu>,
    Michael Mulhearn <michaeljmulhearn@gmail.com>,
    Martin Grunewald <Martin.Grunewald@cern.ch>,
    Andrea Perrotta <andrea.perrotta@bo.infn.it>
Subject: Talk on L1 Offline Software this Thursday
```

which is also put here: https://github.com/cms-l1t-offline/cmssw/issues/103#issuecomment-173523977

The modules listed there are covered above!

**Comment by Martin-Grunewald** [comment]
@fwyzard 
Could you please take care of the TriggerResultsFilter[FromDB]?

**Comment by fwyzard** [comment]
Not before March 1st.

.A

**Comment by Martin-Grunewald** [comment]
Migration to stage-2 L1T - still to do:
- TriggerResultsFilter[FromDB]
- HLTLevel1ActivityFilter
- TriggerSummaryAnalyzer AOD and RAW
- HLTEventAnalyzer AOD and RAW (needs L1GtUtils replacement from L1T)
- HLTPrescaleProvider (needs L1GtUtils replacement from L1T)

**Comment by Martin-Grunewald** [comment]
Close as resolved
