### ISSUE TITLE
Final steps for migration from ConfDB V1 to ConfDB V2 for offline

### ISSUE THREAD

**Issue by Martin-Grunewald** [cms-tsg-storm/cmssw#4]
@fwyzard @sandrov

Here is a summary with information and changes required to complete the ConfDB V1-to-V2 migration for offline. 

Please check that this is indeed correct and complete!

browser:  https://cmsweb.cern.ch/confdb - OK

java gui web links:
V1: http://confdb.web.cern.ch/confdb/v1/gui/ 
V2: http://confdb.web.cern.ch/confdb/v2/gui/

java gui source code (needed for [local] builds of the gui):
github repo https://github.com/cms-sw/hlt-confdb
V1: branch "master" (currently default, ie, for checkout in scripts etc.)
V2: branch "confdbv2" (needs to become the default, for [default] checkouts etc.)

Affected files in CMSSW:

1) options.py:
https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/HLTrigger/Configuration/python/Tools/options.py needs update of connection info and default setting in `class ConnectionHLTMenu(object)`, namely:

```
Valid versions:  v1, v2
Valid databases: online, offline, adg
Compatibility: { 'hltdev': ('v1', 'offline'), 'orcoff': ('v2', 'adg') }
```

2) confdbOfflineConverter.py 
https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/HLTrigger/Configuration/python/Tools/confdbOfflineConverter.py needs update of connection info and default setting in `class OfflineConverter`, namely:

```
    databases = {}
    databases['v1'] = {}
    databases['v1']['offline'] = ( '-t', 'oracle', '-h', 'cmsr1-s.cern.ch',      '-d', 'cms_cond.cern.ch',      '-u', 'cms_hltdev_reader', '-s', 'convertme!' )
    databases['v1']['hltdev']  = databases['v1']['offline']     # for backwards compatibility                                                                                       
    databases['v1']['online']  = ( '-t', 'oracle', '-h', 'cmsonr1-s.cms',        '-d', 'cms_rcms.cern.ch',      '-u', 'cms_hlt_r',         '-s', 'convertme!' )
    databases['v1']['adg']     = ( '-t', 'oracle', '-h', 'cmsr1-s.cern.ch',      '-d', 'cms_cond.cern.ch',      '-u', 'cms_hlt_gui_r',     '-s', 'convertme!' )
    databases['v1']['orcoff']  = databases['v1']['adg']         # for backwards compatibility                                                                                       
    databases['v2'] = {}
    databases['v2']['offline'] = ( '-t', 'oracle', '-h', 'cmsr1-s.cern.ch',      '-d', 'cms_cond.cern.ch',      '-u', 'cms_hlt_gdr_r',     '-s', 'convertme!' )
    databases['v2']['online']  = ( '-t', 'oracle', '-h', 'cmsonr1-s.cms',        '-d', 'cms_rcms.cern.ch',      '-u', 'cms_hlt_gdr_r',     '-s', 'convertme!' )
    databases['v2']['adg']     = ( '-t', 'oracle', '-h', 'cmsonradg1-s.cern.ch', '-d', 'cms_orcon_adg.cern.ch', '-u', 'cms_hlt_gdr_r',     '-s', 'convertme!' )
```

3) hltGetRawConfiguration
https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/HLTrigger/Configuration/scripts/hltGetRawConfiguration uses `git clone` this should be fine if branch "confdbv2" becomes the default (see above), no change needed.

4) hltGetConfiguration
https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/HLTrigger/Configuration/scripts/hltGetConfiguration gets the connection info from options.py, hence once that is updated, no change needed here.

5) hltIntegrationTests
https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/HLTrigger/Configuration/scripts/hltIntegrationTests uses `hltGetConfiguration` and `hltListPaths`, hence no change needed if those two are fixed.

6) hltListPaths
https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/HLTrigger/Configuration/scripts/hltListPaths
uses `hltConfigFromDB` which is just a wrapper for `HLTrigger/Configuration/python/Tools/confdbOfflineConverter.py`, so no update needed if that is fixed.

7) hltConfigFromDB
https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/HLTrigger/Configuration/scripts/hltConfigFromDB is just a wrapper for `HLTrigger/Configuration/python/Tools/confdbOfflineConverter.py``, so no update needed if that is fixed.

8) subtables.sh
https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/HLTrigger/Configuration/tables/subtables.sh
Uses git clone, fine with switch of default github branch to "confdbv2"
Needs update to the following:

```
      DBHOST="cmsr1-v.cern.ch"
      DBNAME="cms_cond.cern.ch"
      DBUSER="cms_hltdev_writer"
      PWHASH="0196d34dd35b04c0f3597dc89fbbe6e2"
```

So as far as I understand it (please check!!), the following changes are needed:
a) make branch "confdbv2" the default branch in github hlt-confdb
b) changes in CMSSW files 1, 2 and 8 above
c) switch off automatic V1=>V2 migration of menus
d) lock V1 to be read only
e) make V2 connection info known in the java GUI pulldown menu itself (where??)
f) changes in ConfDB files located in src/conf/ https://github.com/cms-sw/hlt-confdb/tree/confdbv2/src/conf are already up-to-date in branch "confdbv2"?
g) changes to the (files in the) afs account "confdb" (libraries, gui binaries, whatever??)
h) db, userid and password to be used in GUI login pulldown menu

**Comment by fwyzard** [comment]
> java gui source code (needed for [local] builds of the gui):
> github repo https://github.com/cms-sw/hlt-confdb
> V1: branch "master" (currently default, ie, for checkout in scripts etc.)
> V2: branch "confdbv2" (needs to become the default, for [default] checkouts etc.)

the branch "confdbv2" is now the default; there is a branch "confdbv1" for ConfDB v1.

**Comment by Martin-Grunewald** [comment]
@fwyzard 
Is branch "confdbv1" identical to "master"? Because the latter (also as being the old default) was used throughout by me for V1 work!

**Comment by fwyzard** [comment]
yes, I basically renamed the old "master" to "confdbv1"

**Comment by fwyzard** [comment]
> 1) options.py

all connection strings should be fine already - the only change we should make is to change the default for offline from v1 to v2.

**Comment by fwyzard** [comment]
> 2) confdbOfflineConverter.py 

all connection strings should be fine already - the only change we should make is to change the default for offline from v1 to v2.

**Comment by fwyzard** [comment]
> 3) hltGetRawConfiguration

do we still need `hltGetRawConfiguration` ? or, can we drop it and rely on `hltConfigFromDB` ?

**Comment by fwyzard** [comment]
> 8) subtables.sh

I would like to be able to test this with v2 before committing the changes. @sandrov , is there a test DB for ConfDB v2 with some HLT menus I can play with ?

**Comment by fwyzard** [comment]
> So as far as I understand it (please check!!), the following changes are needed:
> a) make branch "confdbv2" the default branch in github hlt-confdb

done

> b) changes in CMSSW files 1, 2 and 8 above

will do

> c) switch off automatic V1=>V2 migration of menus
> d) lock V1 to be read only
> e) make V2 connection info known in the java GUI pulldown menu itself (where??)

these should already be there in the ConfDB v2 GUI - if not, we can add them and publish an update.

> f) changes in ConfDB files located in src/conf/ https://github.com/cms-sw/hlt-confdb/tree/confdbv2/src/conf are already up-to-date in branch "confdbv2"?

see e)

> g) changes to the (files in the) afs account "confdb" (libraries, gui binaries, whatever??)

done

> h) db, userid and password to be used in GUI login pulldown menu

see e)

**Comment by Martin-Grunewald** [comment]
@fwyzard 
Your PRs https://github.com/cms-sw/cmssw/pull/15697 and https://github.com/cms-sw/cmssw/pull/15696 address two files but not the file subtables.sh (used to generate subtables from the
HLT master table). What is the status there?

**Comment by Martin-Grunewald** [comment]
Resolved....
